// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.CancelCustomerDocumentDelivery;

/// <summary>Withdraw a document that has not been handed to WhatsApp yet.</summary>
public sealed class CancelCustomerDocumentDeliveryHandler(
    ICustomerDocumentService service,
    ILogger<CancelCustomerDocumentDeliveryHandler> logger
) : IRequestHandler<CancelCustomerDocumentDeliveryCommand, ErrorOr<CustomerDocumentDeliveryModel>>
{
    public Task<ErrorOr<CustomerDocumentDeliveryModel>> Handle(CancelCustomerDocumentDeliveryCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.CancelAsync(request.DeliveryId, cancellationToken),
            "The send could not be withdrawn.",
            logger,
            "CancelCustomerDocumentDelivery");
}
