// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.CancelCustomerDocumentDelivery;

/// <summary>Withdraw a document that has not been handed to WhatsApp yet.</summary>
public sealed record CancelCustomerDocumentDeliveryCommand(long DeliveryId) : IRequest<ErrorOr<CustomerDocumentDeliveryModel>>;
