// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.PreviewInvoiceWhatsApp;

/// <summary>The PDF and caption sending the invoice would send now, or why it would wait.</summary>
public sealed record PreviewInvoiceWhatsAppQuery(int DocEntry) : IRequest<ErrorOr<InvoiceWhatsAppPreviewModel>>;
