// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.PreviewInvoiceWhatsApp;

/// <summary>The PDF and caption sending the invoice would send now, or why it would wait.</summary>
public sealed class PreviewInvoiceWhatsAppHandler(
    ICustomerDocumentService service,
    ILogger<PreviewInvoiceWhatsAppHandler> logger
) : IRequestHandler<PreviewInvoiceWhatsAppQuery, ErrorOr<InvoiceWhatsAppPreviewModel>>
{
    public Task<ErrorOr<InvoiceWhatsAppPreviewModel>> Handle(PreviewInvoiceWhatsAppQuery request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.PreviewInvoiceAsync(request.DocEntry, cancellationToken),
            "The document could not be prepared for a preview.",
            logger,
            "PreviewInvoiceWhatsApp");
}
