// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.GetCustomerDocumentDeliveryStatus;

/// <summary>The switches, today's sends against the caps, and what is waiting.</summary>
public sealed record GetCustomerDocumentDeliveryStatusQuery : IRequest<ErrorOr<CustomerDocumentDeliveryStatusModel>>;
