// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.GetCustomerDocumentDeliveryStatus;

/// <summary>The switches, today's sends against the caps, and what is waiting.</summary>
public sealed class GetCustomerDocumentDeliveryStatusHandler(
    ICustomerDocumentService service,
    ILogger<GetCustomerDocumentDeliveryStatusHandler> logger
) : IRequestHandler<GetCustomerDocumentDeliveryStatusQuery, ErrorOr<CustomerDocumentDeliveryStatusModel>>
{
    public Task<ErrorOr<CustomerDocumentDeliveryStatusModel>> Handle(GetCustomerDocumentDeliveryStatusQuery request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.GetStatusAsync(cancellationToken),
            "The WhatsApp delivery status could not be loaded.",
            logger,
            "GetCustomerDocumentDeliveryStatus");
}
