namespace ShopInventory.Configuration;

/// <summary>
/// Which of a route's two departure times decides whether the day was late.
/// </summary>
public enum DepartureVerdictSource
{
    /// <summary>
    /// The first event that put the van outside <see cref="CartrackSettings.DepotRadiusMetres"/>
    /// of where the day's departure was recorded. This is what "the van left" means.
    /// </summary>
    FirstMovement = 0,

    /// <summary>
    /// The first ignition-on of the trading day. Earlier than departure by however long the
    /// driver spent warming a diesel or pulling the box down to temperature, so it grades a
    /// cold morning as an early start.
    /// </summary>
    IgnitionOn = 1,

    /// <summary>
    /// What the rep tapped on the handset — the rule as it stood before any of this. Worth
    /// running for the first week: the report still shows the vehicle's time and the difference
    /// beside it, so the two can be compared over real rounds before anybody is graded on a
    /// pipeline that has never parsed a live response.
    /// </summary>
    Handset = 2
}

/// <summary>
/// The Cartrack Fleet API — the fleet telematics behind the departure compliance report.
/// </summary>
/// <remarks>
/// <para>
/// Credentials are generated by an administrator in Fleetweb under API Settings, not issued by
/// Cartrack support. In production they are <c>Cartrack__Username</c> and
/// <c>Cartrack__Password</c> environment variables in <c>web.config</c>; locally they belong in
/// user secrets. Never in <c>appsettings.json</c>.
/// </para>
/// <para>
/// <see cref="Enabled"/> is false by default. This is an external system with per-endpoint rate
/// limits shared with the vendor's other customers, so a deployment opts in rather than having
/// to remember to opt out.
/// </para>
/// </remarks>
public class CartrackSettings
{
    public const string SectionName = "Cartrack";

    /// <summary>Whether anything talks to Cartrack at all. Off unless a deployment says otherwise.</summary>
    public bool Enabled { get; set; }

    /// <summary>
    /// The regional Fleet API host. Cartrack runs one per country and they are not interchangeable
    /// — an account on the Zimbabwe host does not authenticate against the South African one.
    /// </summary>
    public string BaseUrl { get; set; } = "https://fleetapi-zw.cartrack.com/rest";

    /// <summary>The Fleetweb API user. Not the console login.</summary>
    public string Username { get; set; } = string.Empty;

    /// <summary>The generated API password. Comes from web.config in production.</summary>
    public string Password { get; set; } = string.Empty;

    /// <summary>Whether both halves of the Basic credential are present.</summary>
    public bool HasCredentials =>
        !string.IsNullOrWhiteSpace(Username) && !string.IsNullOrWhiteSpace(Password);

    public int TimeoutSeconds { get; set; } = 60;

    public int MaxRetries { get; set; } = 3;

    /// <summary>
    /// Retry backoff in milliseconds, the last value repeated once exhausted.
    /// </summary>
    /// <remarks>
    /// Empty by default and NOT pre-seeded: the configuration binder appends to a non-empty
    /// collection initializer rather than replacing it, so three defaults plus three in
    /// appsettings.json bind to six. <see cref="EffectiveRetryDelaysMs"/> supplies the fallback.
    /// </remarks>
    public int[] RetryDelaysMs { get; set; } = [];

    /// <inheritdoc cref="RetryDelaysMs"/>
    public int[] EffectiveRetryDelaysMs =>
        RetryDelaysMs.Length > 0 ? RetryDelaysMs : [500, 2000, 5000];

    /// <summary>
    /// The longest a 429's own retry-after is honoured before the call gives up instead.
    /// </summary>
    /// <remarks>
    /// Cartrack answer a throttled request with <c>X-RateLimit-Retry-After-Seconds</c>. Sleeping
    /// for whatever it says would let one response park a background job for an unbounded time;
    /// past this the job stops cleanly on its checkpoint and picks the work up next run.
    /// </remarks>
    public int MaxRetryAfterSeconds { get; set; } = 120;

    /// <summary>
    /// Rows per page on a list call. The API's own default is <b>10</b>, so this must be sent
    /// explicitly or a day of events arrives in a hundred requests.
    /// </summary>
    public int PageSize { get; set; } = 500;

    /// <summary>A hard stop on the pagination loop, so a mis-read envelope cannot spin forever.</summary>
    public int MaxPages { get; set; } = 200;

    /// <summary>
    /// The published request ceilings, per minute. Scalars rather than a dictionary for the same
    /// binder reason as <see cref="RetryDelaysMs"/>.
    /// </summary>
    public int GlobalRequestsPerMinute { get; set; } = 1000;

    /// <inheritdoc cref="GlobalRequestsPerMinute"/>
    public int StatusRequestsPerMinute { get; set; } = 60;

    /// <inheritdoc cref="GlobalRequestsPerMinute"/>
    public int EventsRequestsPerMinute { get; set; } = 60;

    /// <summary>
    /// How far back the first run reaches. Thirty days rather than a quarter because the events
    /// endpoint is capped at 24 hours per call and paginated, so history is the expensive axis —
    /// and nobody audits departure compliance for last quarter.
    /// </summary>
    public int BackfillDays { get; set; } = 30;

    /// <summary>Days of backfill one run may do, so a cold start spreads over nights.</summary>
    public int MaxBackfillDaysPerRun { get; set; } = 7;

    /// <summary>
    /// How far back the daily reconciliation pass re-reads. Cartrack reprocess fuel accuracy after
    /// the fact and late events are normal, so yesterday's numbers are not final.
    /// </summary>
    public int ReconciliationWindowDays { get; set; } = 3;

    /// <summary>Past this, the rollup is stale and the report says so rather than showing it as fact.</summary>
    public int RollupReadyMaxAgeHours { get; set; } = 36;

    public int LivePollIntervalSeconds { get; set; } = 180;

    /// <summary>The CAT window the live poll runs in. Outside it the fleet is parked.</summary>
    public string LivePollFromCat { get; set; } = "04:00";

    /// <inheritdoc cref="LivePollFromCat"/>
    public string LivePollToCat { get; set; } = "20:00";

    /// <summary>Past this, a live position is shown with its age rather than as where the van is.</summary>
    public int LiveStaleAfterSeconds { get; set; } = 900;

    /// <summary>
    /// Two years. Cartrack keep temperature for about two months, so anything longer than that is
    /// only available here — and a food business is asked for cold-chain evidence long after.
    /// </summary>
    public int TemperatureSampleRetentionDays { get; set; } = 730;

    /// <summary>
    /// The longest a single probe reading is taken to hold. A silence longer than this is a gap
    /// in the evidence, not time spent warm, so it cannot stretch one bad reading into a long
    /// breach. See <see cref="Services.Telematics.ColdChainEvaluator"/>.
    /// </summary>
    public int TemperatureSampleGapCapMinutes { get; set; } = 30;

    /// <summary>
    /// Which time decides <c>LateOut</c>. See <see cref="Configuration.DepartureVerdictSource"/>
    /// — this is the one setting that changes whose day is marked late.
    /// </summary>
    public DepartureVerdictSource DepartureVerdictSource { get; set; } =
        DepartureVerdictSource.FirstMovement;

    /// <summary>
    /// How far the handset and the vehicle may disagree before the row says so. Never a
    /// compliance failure on its own — a clock that disagrees with an ignition switch is a
    /// question, not a finding against the rep.
    /// </summary>
    public int DepartureDiscrepancyToleranceMinutes { get; set; } = 10;

    /// <summary>
    /// How far from the recorded departure point the van has to be before it counts as having
    /// left, rather than having been started.
    /// </summary>
    public int DepotRadiusMetres { get; set; } = 250;

    /// <summary>
    /// How far the vehicle's distance may differ from the rep's two odometer readings before the
    /// row says so. Both a floor and a percentage, because the vehicle accumulates metres while
    /// the rep subtracts two whole kilometres — the vehicle figure is almost always a little
    /// higher, and a 3 km gap is not a finding.
    /// </summary>
    public int OdometerToleranceKm { get; set; } = 5;

    /// <inheritdoc cref="OdometerToleranceKm"/>
    public int OdometerTolerancePercent { get; set; } = 10;
}
