// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.RequestInvoiceWhatsApp;

/// <summary>Queue an invoice for the customer's WhatsApp. Nothing is sent here; the delivery job sends it.</summary>
public sealed class RequestInvoiceWhatsAppHandler(
    ICustomerDocumentService service,
    ILogger<RequestInvoiceWhatsAppHandler> logger
) : IRequestHandler<RequestInvoiceWhatsAppCommand, ErrorOr<List<CustomerDocumentDeliveryModel>>>
{
    public Task<ErrorOr<List<CustomerDocumentDeliveryModel>>> Handle(RequestInvoiceWhatsAppCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.RequestInvoiceAsync(request.DocEntry, request.Recipients, cancellationToken),
            "The invoice could not be queued for WhatsApp.",
            logger,
            "RequestInvoiceWhatsApp");
}
