// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.RequestInvoiceWhatsApp;

/// <summary>Queue an invoice for the customer's WhatsApp. Nothing is sent here; the delivery job sends it.</summary>
public sealed record RequestInvoiceWhatsAppCommand(int DocEntry, RequestInvoiceWhatsAppModel Recipients) : IRequest<ErrorOr<List<CustomerDocumentDeliveryModel>>>;
