// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.UpdateCustomerDocumentDeliverySettings;

/// <summary>Choose the sending session, switch automatic sending, and set its daily cap.</summary>
public sealed class UpdateCustomerDocumentDeliverySettingsHandler(
    ICustomerDocumentService service,
    ILogger<UpdateCustomerDocumentDeliverySettingsHandler> logger
) : IRequestHandler<UpdateCustomerDocumentDeliverySettingsCommand, ErrorOr<CustomerDocumentDeliveryStatusModel>>
{
    public Task<ErrorOr<CustomerDocumentDeliveryStatusModel>> Handle(UpdateCustomerDocumentDeliverySettingsCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.UpdateSettingsAsync(request.Settings, cancellationToken),
            "The settings could not be saved.",
            logger,
            "UpdateCustomerDocumentDeliverySettings");
}
