// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.UpdateCustomerDocumentDeliverySettings;

/// <summary>Choose the sending session, switch automatic sending, and set its daily cap.</summary>
public sealed record UpdateCustomerDocumentDeliverySettingsCommand(UpdateCustomerDocumentDeliverySettingsModel Settings) : IRequest<ErrorOr<CustomerDocumentDeliveryStatusModel>>;
