// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.GetCustomerWhatsAppContacts;

/// <summary>The WhatsApp numbers saved on one customer: a SAP card or a route customer.</summary>
public sealed record GetCustomerWhatsAppContactsQuery(string? CardCode, int? RouteCustomerId) : IRequest<ErrorOr<List<CustomerWhatsAppContactModel>>>;
