// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.GetCustomerWhatsAppContacts;

/// <summary>The WhatsApp numbers saved on one customer: a SAP card or a route customer.</summary>
public sealed class GetCustomerWhatsAppContactsHandler(
    ICustomerDocumentService service,
    ILogger<GetCustomerWhatsAppContactsHandler> logger
) : IRequestHandler<GetCustomerWhatsAppContactsQuery, ErrorOr<List<CustomerWhatsAppContactModel>>>
{
    public Task<ErrorOr<List<CustomerWhatsAppContactModel>>> Handle(GetCustomerWhatsAppContactsQuery request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.GetContactsAsync(request.CardCode, request.RouteCustomerId, cancellationToken),
            "The customer's WhatsApp numbers could not be loaded.",
            logger,
            "GetCustomerWhatsAppContacts");
}
