// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopInventory.Web.Data;

#nullable disable

namespace ShopInventory.Web.Migrations
{
    [DbContext(typeof(WebAppDbContext))]
    [Migration("20260104055937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopInventory.Web.Data.CacheSyncInfo", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SyncSuccessful")
                        .HasColumnType("boolean");

                    b.HasKey("CacheKey");

                    b.ToTable("CacheSyncInfo", (string)null);
                });

            modelBuilder.Entity("ShopInventory.Web.Data.CachedProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BarCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DefaultWarehouse")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ItemType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ManagesBatches")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("UoM")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ItemCode");

                    b.HasIndex("BarCode");

                    b.HasIndex("IsActive");

                    b.HasIndex("ItemName");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("CachedProducts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
