// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.RetryCustomerDocumentDelivery;

/// <summary>Send a document again, as a new delivery that records the one it replaces.</summary>
public sealed class RetryCustomerDocumentDeliveryHandler(
    ICustomerDocumentService service,
    ILogger<RetryCustomerDocumentDeliveryHandler> logger
) : IRequestHandler<RetryCustomerDocumentDeliveryCommand, ErrorOr<CustomerDocumentDeliveryModel>>
{
    public Task<ErrorOr<CustomerDocumentDeliveryModel>> Handle(RetryCustomerDocumentDeliveryCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.RetryAsync(request.DeliveryId, request.ConfirmNotReceived, cancellationToken),
            "The document could not be sent again.",
            logger,
            "RetryCustomerDocumentDelivery");
}
