// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.RetryCustomerDocumentDelivery;

/// <summary>Send a document again, as a new delivery that records the one it replaces.</summary>
public sealed record RetryCustomerDocumentDeliveryCommand(long DeliveryId, bool ConfirmNotReceived) : IRequest<ErrorOr<CustomerDocumentDeliveryModel>>;
