// <auto-generated>
//     Generated by scripts/DeliveryRoutes/generate_delivery_routes.py from
//     "REVISED  ROUTES 2026.xlsx", sheet "PROPOSED ROUTES", with every business partner code
//     resolved against the SAP customer master. Do not edit by hand -- re-run
//     the generator when the routes change.
// </auto-generated>

namespace ShopInventory.Web.Common;

public static partial class DeliveryRoutes
{
    private static readonly DeliveryRoute[] RouteTable =
    [
        new("BORROWDALE", ["Tuesday"], ["10T"],
        [
            "ESK001 USD", // Eskbank
            "HAR001", // Farmwealth Investments T/A Harry's
            "MOR004", // Morsten Enterprises (Pvt) Ltd T/A Billy's Meats USD
            "SPA002", // Spar Bridge Yellowcob Ent P/L t/a
            "SPA003", // Spar Golden Stairs Yellowcob Ent t/a
            "SPA005", // Spar Borrowdale Village Yellowcob Ent P/L t/a
            "SPA010", // SPAR Ballantyne Yellowcob Ent P/L t/a
            "SPA050 USD", // Spar Bridge Yellowcob Ent P/L t/a
            "SPA051 USD", // Spar Golden Stairs Yellowcob Ent t/a
            "SPA053 USD", // Spar Borrowdale Village Yellowcob Ent P/L t/a
            "SPA058 USD", // SPAR Ballantyne Yellowcob Ent P/L t/a
            "SPA070", // Spar Bridge Yellowcob Ent P/L t/a ZiG
            "SPA074", // Spar Cardinals
            "SPI001", // F.M Leeya Ent P/L T/A Spice Hub
        ]),
        new("BULAWAYO", ["Monday", "Friday"], ["24T"],
        [
            "CHE001", // Cheese Galore RTGS
            "CHE005 (FCA)", // Cheese Galore
            "CHE006", // Cheese Galore (Packaging)
            "CHE010", // Cheese Galore (Packaging)
            "CHE012", // Cheese Galore (Packaging)
            "CHE013", // Cheese Galore ZiG
            "CHE016 ZIG", // Cheese Galore (Packaging)
            "CHE020", // Cheese Galore
        ]),
        new("CBD1-CHITUNGWIZA", ["Thursday"], ["24T"],
        [
            "BHO016", // Bhola Mega Mart Sunningdale
            "GAI006", // GAINS GRANITESIDE
            "GAI079", // Metropeech hypermarket Seke Road
            "NRI006", // N Richards Graniteside
            "NRI037", // N Richards Graniteside USD
            "SPA009", // SPAR Waterfalls Yellowcob Ent P/L t/a
            "SPA021", // SPAR Hatfield Yellowcob Ent P/L t/a
            "SPA057 USD", // SPAR Waterfalls Yellowcob Ent P/L t/a
            "SPA062 USD", // SPAR Hatfield Yellowcob Ent P/L t/a
            "TMP015", // Tm Zengeza 2
            "TMP021", // TM Makoni Chitungwiza
            "TMP078", // Tm Zengeza 2 USD
            "TMP086", // TM Makoni Chitungwiza USD
            "TMP142", // Tm Zengeza 2 ZiG
            "TMP150", // TM Makoni Chitungwiza ZiG
        ]),
        new("CBD2", ["Thursday"], ["10T"],
        [
            "ALA002", // Alaska Stop And Shop (Pvt) Ltd
            "ASS003", // Associated Meat Packers Pvt Ltd/TA AMP Meats
            "ASS005", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Westgate)
            "ASS006", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Coventry)
            "ASS009 USD", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Coventry)
            "ASS010 USD", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Westagate)
            "ASS011 USD", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Greenfields)
            "ASS012 USD", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Coventry)
            "BHO011", // Bhola Mega Mart Tynwald
            "BHO012", // Bhola Whiteclif USD
            "BHO014", // Bhola Hardware Workington
            "BHO017", // Bhola Mega Mart Warren Park
            "FOO008", // Food World Cam Speke
            "FOO028", // Food World Cam Speke USD
            "FOO044", // Food World Cam Speke ZiG
            "LAN010", // Lanwood Trading Pvt Ltd T/A Megasave Workington
            "MAP001", // Maplanka Meat Market
            "MAP002", // Maplanka Meat Market FCA
            "MAP003", // Maplanka Meat Market ZiG
            "NYA009", // Nyaningwe Investments - Warren Park 1
        ]),
        new("HARARE CHILLER", ["Monday"], ["24T"],
        [
            "CHE001", // Cheese Galore RTGS
            "CHE005 (FCA)", // Cheese Galore
            "CHE006", // Cheese Galore (Packaging)
            "CHE010", // Cheese Galore (Packaging)
            "CHE012", // Cheese Galore (Packaging)
            "CHE013", // Cheese Galore ZiG
            "CHE016 ZIG", // Cheese Galore (Packaging)
            "CHE020", // Cheese Galore
        ]),
        new("HONEYDEW", ["Wednesday"], ["10T"],
        [
            "FRU003 USD", // Frugiparus Enterprises
        ]),
        new("KARIBA", ["Tuesday"], ["10T"],
        [
            "CHI010", // Chirundu Staff Canteen
            "FRA002", // Francberg Investments T/A Dairyfresh Distributors kariba
            "FRA003 ZIG", // Francberg Investments T/A Dairyfresh Distributors kariba
            "GAI015", // GAINS CHEGUTU
            "GAI117", // Gain Metro Chegutu
            "GIJ001", // Gijazy Investments Pvt Limited
            "LAN011", // Lanwood Trading Pvt Ltd T/A Megasave Karoi
            "LAN017", // Lanwood Trading Pvt Ltd T/A Megasave Chinhoyi
            "NRI010", // N Richards Chinhoyi
            "NRI022", // N Richards Karoi
            "NRI041", // N Richards Chinhoyi USD
            "NRI054", // N Richards Karoi USD
            "TMP003", // TM Kariba
            "TMP010", // TM Chinhoyi South
            "TMP014", // TM Karoi
            "TMP018", // Tm Chinhoyi North
            "TMP022", // Tm Norton
            "TMP066", // TM Kariba USD
            "TMP073", // TM Chinhoyi South USD
            "TMP077", // TM Karoi USD
            "TMP083", // Tm Chinhoyi North USD
            "TMP087", // Tm Norton USD
            "TMP130", // TM Kariba ZiG
            "TMP137", // TM Chinhoyi South ZiG
            "TMP141", // TM Karoi ZiG
            "TMP147", // Tm Chinhoyi North ZiG
            "TMP151", // Tm Norton ZiG
        ]),
        new("MARONDERA-CHIPINGE", ["Tuesday"], ["24T"],
        [
            "ANG002", // Angelight Ent T/A Total Rusape
            "ANG004 USD", // Angelight Ent T/A Total Rusape
            "BHO003 USD", // Bhola Mega Mart Rusape
            "BHO004 USD", // Bhola Mega Mart Mutare
            "BHO013", // Bhola Supermarket Mutare Town
            "BHO023", // BHOLA SUPERMARKET - MARONDERA
            "CYB004", // Zuva Aerodrome
            "DCK001", // DCK Supermarket Brainman Inv t/a
            "DCK002 USD", // DCK Supermarket Brainman Inv t/a
            "GAI102", // Metropeech Hypermarket Mutare
            "GAI103", // Metro Peech Hypermarket Chipinge
            "GAI113", // Gains Cash and Carry Sakubva
            "GAI118", // Gain Cash & Carry Wholesale Checheche
            "GLO004 USD", // Global Brothers Wholesalers Pvt Ltd
            "LAN013", // Lanwood Trading Pvt Ltd T/A Megasave Marondera
            "MAU001", // Mauriberg Investment T/A Panmart Rusape
            "MAU002", // Mauriberg Investment T/A Panmart Mutare
            "MAU003", // Mauriberg Investment T/A Panmart Rusape ZiG
            "MAU004", // Mauriberg Investment T/A Panmart Mutare ZiG
            "NRI003", // N Richards Marondera
            "NRI013", // N Richards Rusape
            "NRI034", // N Richards Marondera USD
            "NRI044", // N Richards Rusape USD
            "OKM005", // OK Mart Mutare
            "OKM012", // OK Mart Mutare USD
            "OKM022", // OK Mart Mutare ZiG
            "OKM025", // OK Mart Mutare ZiG
            "OKZ042", // OK Rusape
            "OKZ096", // OK Rusape USD
            "OKZ151", // OK Rusape ZiG
            "SAI021", // Sai Mart - Mutare
            "SAV001", // SAV Wholesalers Restan t/a
            "SAV002 USD", // SAV Wholesalers Restan t/a
            "SPA026", // Spar Mutare Yellowcob Ent P/L t/a
            "SPA035", // SPAR Marondera Yellowcob Ent P/L t/a
            "SPA065 USD", // Spar Mutare Yellowcob Ent P/L t/a
            "SPA067 USD", // SPAR Marondera Yellowcob Ent P/L t/a
            "TAR003 USD", // Taramyn Pvt Ltd
            "TMP024", // TM Main Street Marondera
            "TMP038", // TM Main Street Mutare
            "TMP040", // TM Chipinge
            "TMP042", // TM Rusape
            "TMP044", // TM Sakubva Mutare
            "TMP089", // TM Main Street Marondera USD
            "TMP102", // TM Main Street Mutare USD
            "TMP104", // TM Chipinge USD
            "TMP106", // TM Rusape USD
            "TMP108", // TM Sakubva Mutare USD
            "TMP153", // TM Main Street Marondera ZiG
            "TMP166", // TM Main Street Mutare ZiG
            "TMP168", // TM Chipinge ZiG
            "TMP170", // TM Rusape ZiG
            "TMP172", // TM Sakubva Mutare ZiG
        ]),
        new("MIDLANDS 1", ["Wednesday"], ["18T"],
        [
            "CRE006", // Credle Enterprises Pvt Ltd
            "GAI078", // Heart groove t/a Metro Hyper Gweru
            "GAI114", // Metro Peech Hypermarket Kwekwe
            "NRI007", // N Richards Gweru
            "NRI029", // N Richards Kwekwe
            "NRI031", // N Richards Kadoma
            "NRI038", // N Richards Gweru USD
            "NRI061", // N Richards Kwekwe USD
            "NRI063", // N Richards Kadoma USD
            "NYA005 USD", // Nyaningwe Wholesalers Gweru
            "OKM003", // OK Mart Gweru
            "OKM004", // OK Mart Kwekwe
            "OKM010", // OK Mart Gweru USD
            "OKM011", // OK Mart Kwekwe USD
            "OKM019", // OK Mart Gweru ZiG
            "OKM020", // OK Mart Kwekwe ZiG
            "OKZ007", // OK Kadoma
            "OKZ009", // OK Chegutu
            "OKZ063", // OK Kadoma USD
            "OKZ065", // OK Chegutu USD
            "OKZ118", // OK Kadoma ZiG
            "OKZ120", // OK Chegutu ZiG
            "SAI012", // Sai Mart - Gokwe
            "SAI014", // Sai Mart - Gweru (New shop)
            "SAI020", // Sai Mart - Mkoba
            "SPA013", // SPAR Kadoma
            "SPA025", // SPAR Kwekwe Yellowcob Ent t/a
            "SPA036 FCA", // SPAR Kadoma
            "SPA064 USD", // SPAR Kwekwe Yellowcob Ent t/a
            "SPA075", // Spar Express Kadoma
            "TMP005", // TM Kwekwe Main Street
            "TMP006", // TM Kadoma
            "TMP019", // Tm Zvishavane
            "TMP030", // Pick n Pay Gweru
            "TMP037", // Pick n Pay Megawatt Gweru
            "TMP068", // TM Kwekwe Main Street USD
            "TMP069", // TM Kadoma USD
            "TMP084", // Tm Zvishavane USD
            "TMP095", // Pick n Pay Gweru USD
            "TMP101", // Pick n Pay Megawatt Gweru USD
            "TMP132", // TM Kwekwe Main Street ZiG
            "TMP133", // TM Kadoma ZiG
            "TMP148", // Tm Zvishavane ZiG
            "TMP159", // Pick n Pay Gweru ZiG
            "TMP165", // Pick n Pay Megawatt Gweru ZiG
            "TMP196", // TM Shurugwi ZiG
            "TMP197", // TM Shurugwi USD
        ]),
        new("MIDLANDS 2", ["Tuesday"], ["14T"],
        [
            "BHO005 USD", // Bhola Mega Mart Masvingo
            "GAI054", // GAINS CHIREDZI
            "GAI076", // Metro peech hypermarket Masvingo
            "GAI110", // Gains Cash and Carry Triangle
            "GAI111", // Metro Hypermarket Chiredzi
            "NRI004", // N Richards Masvingo Cash & Carry
            "NRI008", // N Richards Chivhu
            "NRI011", // N Richards Zvishavane
            "NRI015", // N Richards Chiredzi Cash & Carry
            "NRI016", // N Richards Chivi
            "NRI019", // N Richards Masvingo Wholesale
            "NRI021", // N Richards Chivhu
            "NRI023", // N Richards & Co Masvingo Pvt T/A N Richards Jerera
            "NRI024", // N Richards Chiredzi Wholesale
            "NRI026", // N Richards & Co Masvingo Pvt T/A N Richards Bradburn
            "NRI027", // N Richards & Co Masvingo Pvt ( Mupandawana)
            "NRI028", // N Richards & Co Masvingo Pvt ( Nyika)
            "NRI030", // N Richards Zvishavane
            "NRI035", // N Richards Masvingo Cash & Carry USD
            "NRI039", // N Richards Chivhu USD
            "NRI042", // N Richards Zvishavane USD
            "NRI046", // N Richards Chiredzi Cash & Carry USD
            "NRI047", // N Richards Chivi USD
            "NRI051", // N Richards Masvingo Wholesale USD
            "NRI053", // N Richards Chivhu USD
            "NRI055", // N Richards & Co Masvingo Pvt T/A N Richards Jerera USD
            "NRI056", // N Richards Chiredzi Wholesale USD
            "NRI058", // N Richards & Co Masvingo Pvt T/A N Richards Bradburn USD
            "NRI059", // N Richards & Co Masvingo Pvt ( Mupandawana) USD
            "NRI060", // N Richards & Co Masvingo Pvt ( Nyika) USD
            "NRI062", // N Richards Zvishavane USD
            "OKM006", // OK Mart Masvingo
            "OKM013", // OK Mart Masvingo USD
            "OKM017", // OK Mart Masvingo USD
            "OKM024", // OK Mart Masvingo ZiG
            "SPA023", // N and R Ent t/a Balmain SPAR
            "SPA040", // N and R Ent t/a Balmain SPAR USD
            "TMP028", // Pick n Pay Masvingo
            "TMP039", // TM Chiredzi
            "TMP041", // TM Triangle
            "TMP058", // Pick n Pay Chivhu
            "TMP093", // Pick n Pay Masvingo USD
            "TMP103", // TM Chiredzi USD
            "TMP105", // TM Triangle USD
            "TMP122", // Pick n Pay Chivhu USD
            "TMP157", // Pick n Pay Masvingo ZiG
            "TMP167", // TM Chiredzi ZiG
            "TMP169", // TM Triangle ZiG
            "TMP186", // Pick n Pay Chivhu ZiG
        ]),
        new("MSASA", ["Wednesday"], ["14T"],
        [
            "BHO001 USD", // Bhola Mega Mart Msasa
            "BHO019", // Bhola Mega Mart Mabvuku
            "BHO021", // BHOLA SUPERMARKET - MABVUKU
            "CYB001", // Cybrex Private Limited
            "CYB002 USD", // Cybrex Private Limited
            "GAI115", // Metro Hypermarket Msasa
            "SPA004", // Spar Letombo Yellowcob Ent t/a
            "SPA007", // SPAR Braeside Yellowcob Ent P/L t/a
            "SPA012", // SPAR Arcadia Yellowcob Ent P/: t/a
            "SPA052 USD", // Spar Letombo Yellowcob Ent t/a
            "SPA055 USD", // SPAR Braeside Yellowcob Ent P/L t/a
            "SPA060", // SPAR Arcadia Yellowcob Ent P/: t/a
            "TMP008", // TM Ruwa
            "TMP031", // Pick n Pay Msasa
            "TMP071", // TM Ruwa USD
            "TMP096", // Pick n Pay Msasa USD
            "TMP135", // TM Ruwa ZiG
            "TMP160", // Pick n Pay Msasa ZiG
        ]),
        new("MVURWI-BIND/MTOKO", ["Thursday"], ["10T"],
        [
            "LAN007", // Lanwood Trading Pvt Ltd T/A Megasave Shamva
            "LAN008", // Lanwood Trading Pvt Ltd T/A Megasave Mvurwi
            "LAN009", // Lanwood Trading Pvt Ltd T/A Megasave Mt darwin
            "LAN012", // Lanwood Trading Pvt Ltd T/A Megasave Glendale
            "SPA076", // Spar Mazoe
            "TMP004", // TM Machipisa
            "TMP013", // TM Budiriro
            "TMP020", // Tm Bindura
            "TMP025", // TM Mutoko
            "TMP067", // TM Machipisa USD
            "TMP076", // TM Budiriro USD
            "TMP085", // Tm Bindura USD
            "TMP090", // TM Mutoko USD
            "TMP131", // TM Machipisa ZiG
            "TMP140", // TM Budiriro ZiG
            "TMP149", // Tm Bindura ZiG
            "TMP154", // TM Mutoko ZiG
        ]),
        new("PNP CENTRAL", ["Wednesday"], ["14T"],
        [
            "BHO010 USD", // Bhola Chinhoyi street
            "BHO018", // Bhola Supermarket Robert Mugabe
            "BHO020", // Bhola Supermarket - Nelson Mandela
            "TMP011", // TM Kenneth Kaunda Ave
            "TMP012", // TM Orr Street
            "TMP016", // TM Chadcombe
            "TMP033", // Pick n Pay Second Street
            "TMP035", // Pick n Pay Joina City
            "TMP057", // TM Orr Street
            "TMP060", // Pick n Pay Chiremba Road
            "TMP062", // Pick n Pay Simon Mazorodze
            "TMP074", // TM Kenneth Kaunda Ave USD
            "TMP075", // TM Orr Street USD
            "TMP079", // TM Chadcombe USD
            "TMP097", // Pick n Pay Second Street USD
            "TMP099", // Pick n Pay Joina City USD
            "TMP121", // TM Orr Street USD
            "TMP124", // Pick n Pay Chiremba Road USD
            "TMP126", // Pick n Pay Simon Mazorodze USD
            "TMP138", // TM Kenneth Kaunda Ave ZiG
            "TMP139", // TM Orr Street ZiG
            "TMP143", // TM Chadcombe ZiG
            "TMP161", // Pick n Pay Second Street ZiG
            "TMP163", // Pick n Pay Joina City ZiG
            "TMP185", // TM Orr Street ZiG
            "TMP188", // Pick n Pay Chiremba Road ZiG
            "TMP190", // Pick n Pay Simon Mazorodze ZiG
        ]),
        new("PNP NORTH", ["Monday"], ["14T"],
        [
            "ASS003", // Associated Meat Packers Pvt Ltd/TA AMP Meats
            "ASS005", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Westgate)
            "ASS006", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Coventry)
            "ASS009 USD", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Coventry)
            "ASS010 USD", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Westagate)
            "ASS011 USD", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Greenfields)
            "ASS012 USD", // Associated Meat Packers Pvt Ltd/TA AMP Meats (Coventry)
            "FRE011", // Fresh Select Market Pvt Ltd
            "SHO001", // Shortwaters Trading Pvt Ltd t/a Garfunkels
            "TMP009", // TM Strathaven
            "TMP027", // Pick n Pay Westgate
            "TMP029", // Pick n Pay Arundel
            "TMP034", // Pick n Pay Avondale
            "TMP059", // Pick n Pay Aspindale
            "TMP063", // Pick n Pay Madokero
            "TMP072", // TM Strathaven USD
            "TMP092", // Pick n Pay Westgate USD
            "TMP094", // Pick n Pay Arundel USD
            "TMP098", // Pick n Pay Avondale USD
            "TMP123", // Pick n Pay Aspindale USD
            "TMP127", // Pick n Pay Madokero USD
            "TMP136", // TM Strathaven ZiG
            "TMP156", // Pick n Pay Westgate ZiG
            "TMP158", // Pick n Pay Arundel ZiG
            "TMP162", // Pick n Pay Avondale ZiG
            "TMP187", // Pick n Pay Aspindale ZiG
            "TMP191", // Pick n Pay Madokero ZiG
        ]),
        new("PNP SOUTH", ["Tuesday"], ["14T"],
        [
            "BHO006 USD", // Bhola Mega Mart Hogerty Hill
            "GAI104", // GAINS HATCLIFFE
            "SPA014", // SPAR Kamfinsa Yellowcob Inv t/a
            "SPA024", // SPAR Helensvale Yellowcob Ent t/a
            "SPA061", // SPAR Kamfinsa Yellowcob Inv t/a
            "SPA063 USD", // SPAR Helensvale Yellowcob Ent t/a
            "TMP002", // TM Newlands
            "TMP026", // Pick n Pay Kamfinsa
            "TMP036", // Pick n Pay Borrowdale
            "TMP061", // Pick n Pay Highlands Park
            "TMP065", // TM Newlands USD
            "TMP091", // Pick n Pay Kamfinsa USD
            "TMP100", // Pick n Pay Borrowdale USD
            "TMP125", // Pick n Pay Highlands Park USD
            "TMP129", // TM Newlands ZiG
            "TMP155", // Pick n Pay Kamfinsa ZiG
            "TMP164", // Pick n Pay Borrowdale ZiG
            "TMP189", // Pick n Pay Highlands Park ZiG
            "TMP193", // Pick n Pay Hogerty Hill ZiG
            "TMP198", // Pick n Pay Hogerty Hill USD
        ]),
        new("RICHWELL FREEZER", ["Wednesday"], ["10T"],
        [
            "CHE001", // Cheese Galore RTGS
            "CHE005 (FCA)", // Cheese Galore
            "CHE006", // Cheese Galore (Packaging)
            "CHE010", // Cheese Galore (Packaging)
            "CHE012", // Cheese Galore (Packaging)
            "CHE013", // Cheese Galore ZiG
            "CHE016 ZIG", // Cheese Galore (Packaging)
            "CHE020", // Cheese Galore
        ]),
        new("VICTORIA FALLS", ["Monday"], ["18T"],
        [
            "CHE001", // Cheese Galore RTGS
            "CHE005 (FCA)", // Cheese Galore
            "CHE006", // Cheese Galore (Packaging)
            "CHE010", // Cheese Galore (Packaging)
            "CHE012", // Cheese Galore (Packaging)
            "CHE013", // Cheese Galore ZiG
            "CHE016 ZIG", // Cheese Galore (Packaging)
            "CHE020", // Cheese Galore
            "OKZ049", // OK Hwange
            "OKZ104", // OK Hwange USD
            "OKZ159", // OK Hwange ZiG
            "TMP054", // Pick n Pay Victoria Falls
            "TMP055", // TM Hwange
            "TMP118", // Pick n Pay Victoria Falls USD
            "TMP119", // TM Hwange USD
            "TMP182", // Pick n Pay Victoria Falls ZiG
            "TMP183", // TM Hwange ZiG
            "WID001", // Widebrimm Inv T/A Seven Eleven
            "WID002", // Widebrimm Inv T/A Seven Eleven
        ]),
        new("WEST 1", ["Monday"], ["10T"],
        [
            "BEL004 USD", // Belvedere Trading Nskburg Inv t/a
            "BHO002 USD", // Bhola Mega Mart Longchen Plaza
            "BHO015", // Bhola Supermarket Bishop Gaul
            "BHO025", // Bhola Supermarket Avonlea
            "FOO010", // Foodworld Emporium
            "FOO030", // Foodworld Emporium USD
            "FOO042", // Foodworld Emporium ZiG
            "GAI082", // Metro Hypermarket Tynwald
            "JOL001 USD", // Jolly Jongwe Wholesalers Pvt Ltd
            "SPA071 USD", // SPAR Greenfields
        ]),
        new("WEST 2", ["Monday"], ["10T"],
        [
            "SPA008", // SPAR Montagu Yellowcob Ent P/L t/a
            "SPA011", // SPAR Athienitis Yellowcob Ent P/: t/a
            "SPA016", // Spar Silver Glory (Cash on Collection)
            "SPA017 USD", // Spar Mabelreign
            "SPA019", // SPAR Greencroft
            "SPA056 USD", // SPAR Montagu Yellowcob Ent P/L t/a
            "SPA059 USD", // SPAR Athienitis Yellowcob Ent P/: t/a
            "SPA068 USD", // Spar Silver Glory
            "SPA069 USD", // SPAR Greencroft
        ]),
    ];
}
