using System.Text.RegularExpressions;
using ShopInventory.Common;
using ShopInventory.Features.Invoices.Queries.GetPodUploadStatus;
using ShopInventory.Services;
using Xunit.Abstractions;

namespace ShopInventory.Tests;

/// <summary>
/// Matches the <c>PODCRA_*</c> codes a live company holds against the codes the statement in this
/// repository would produce, so the 841 objects production carries can be attributed rather than
/// guessed at.
/// </summary>
/// <remarks>
/// A content-addressed code is a hash of the statement, which makes it evidence: if a code in SAP
/// is one this build would generate, the object is live and its range is in use. If it is not, the
/// statement that made it has since been edited, and every range it covered was orphaned by that
/// edit — a leak that looks exactly like legitimate range coverage from the outside.
///
/// Reads the census snapshot written by <c>SapSqlQueryCensusTests</c>; skips when there is none, so
/// a plain test run never depends on having contacted SAP.
/// </remarks>
public class PodCrateQueryFingerprintTests
{
    private const string SnapshotVariable = "SHOPINVENTORY_SAP_CENSUS_SNAPSHOT";

    /// <summary>
    /// How far up DocEntry space to look. Well past any plausible invoice count, and cheap: the
    /// whole sweep is a few thousand SHA-256 hashes.
    /// </summary>
    private const int MaxDocEntry = 3_000_000;

    private static readonly Regex PodCrateCode =
        new("^PODCRA_(?<fingerprint>[0-9A-F]{12})$", RegexOptions.Compiled);

    /// <summary>
    /// The crate-classification statement exactly as it stood while it interpolated its range,
    /// frozen here so the rows it left in production stay attributable after the live statement
    /// moved to bound parameters.
    /// </summary>
    /// <remarks>
    /// A copy of production code is normally a drift hazard, which is why this started out calling
    /// the real method. It stopped being one the moment the real statement changed: this text is now
    /// history, and history does not drift. It must NOT be updated to track the live statement —
    /// doing so would silently stop attributing the very objects it exists to identify.
    /// </remarks>
    private static string BuildLegacyCrateInvoiceClassificationSql(int docEntryStart, int docEntryEnd) => $@"
SELECT DISTINCT
    T0.""DocEntry"" AS ""InvoiceDocEntry""
FROM INV1 T0
WHERE T0.""DocEntry"" BETWEEN {docEntryStart} AND {docEntryEnd}
  AND T0.""ItemCode"" IN ('CRA001', 'CRA002', 'CRA003', 'CRA006')
ORDER BY T0.""DocEntry""";

    private readonly ITestOutputHelper _output;

    public PodCrateQueryFingerprintTests(ITestOutputHelper output) => _output = output;

    [Fact]
    public void Attribute_the_pod_crate_query_objects()
    {
        var snapshot = Environment.GetEnvironmentVariable(SnapshotVariable);
        if (string.IsNullOrWhiteSpace(snapshot) || !File.Exists(snapshot))
        {
            _output.WriteLine($"No census snapshot at {SnapshotVariable}; nothing to attribute.");
            return;
        }

        var actual = File.ReadAllLines(snapshot)
            .Select(line => line.Trim())
            .Where(line => PodCrateCode.IsMatch(line))
            .ToHashSet(StringComparer.Ordinal);

        _output.WriteLine($"PODCRA_<12HEX> codes in the company : {actual.Count}");

        // Every aligned bucket the interpolated statement could ever have asked for.
        var expected = new Dictionary<string, (int Start, int End)>(StringComparer.Ordinal);
        for (var start = 0; start < MaxDocEntry; start += SqlIdRangeCover.DefaultBucketSize)
        {
            var end = start + SqlIdRangeCover.DefaultBucketSize - 1;
            var sql = BuildLegacyCrateInvoiceClassificationSql(start, end);
            expected[SAPServiceLayerClient.BuildContentAddressedQueryCode("PODCRA", sql)] = (start, end);
        }

        var matched = actual
            .Where(expected.ContainsKey)
            .Select(code => expected[code])
            .OrderBy(range => range.Start)
            .ToList();

        var unmatched = actual.Count - matched.Count;

        _output.WriteLine($"Generated by the interpolated statement : {matched.Count}");
        _output.WriteLine($"Generated by some earlier statement text: {unmatched}");
        _output.WriteLine(string.Empty);

        if (matched.Count > 0)
        {
            _output.WriteLine($"DocEntry span covered : {matched[0].Start:N0} .. {matched[^1].End:N0}");
            _output.WriteLine($"Buckets in that span  : {(matched[^1].End - matched[0].Start + 1) / SqlIdRangeCover.DefaultBucketSize:N0}");
            _output.WriteLine($"Buckets actually held : {matched.Count:N0}");
            _output.WriteLine(string.Empty);
            _output.WriteLine("First 10 ranges:");
            foreach (var (start, end) in matched.Take(10))
            {
                _output.WriteLine($"  {start,10:N0} .. {end,10:N0}");
            }

            _output.WriteLine("Last 10 ranges:");
            foreach (var (start, end) in matched.TakeLast(10))
            {
                _output.WriteLine($"  {start,10:N0} .. {end,10:N0}");
            }
        }
    }
}
