// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.UpdateCustomerWhatsAppContact;

/// <summary>Change a saved number's contact name, or whether invoices go to it on their own.</summary>
public sealed record UpdateCustomerWhatsAppContactCommand(int ContactId, UpdateCustomerWhatsAppContactModel Changes) : IRequest<ErrorOr<CustomerWhatsAppContactModel>>;
