// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.UpdateCustomerWhatsAppContact;

/// <summary>Change a saved number's contact name, or whether invoices go to it on their own.</summary>
public sealed class UpdateCustomerWhatsAppContactHandler(
    ICustomerDocumentService service,
    ILogger<UpdateCustomerWhatsAppContactHandler> logger
) : IRequestHandler<UpdateCustomerWhatsAppContactCommand, ErrorOr<CustomerWhatsAppContactModel>>
{
    public Task<ErrorOr<CustomerWhatsAppContactModel>> Handle(UpdateCustomerWhatsAppContactCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.UpdateContactAsync(request.ContactId, request.Changes, cancellationToken),
            "The WhatsApp number could not be updated.",
            logger,
            "UpdateCustomerWhatsAppContact");
}
