// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.OptOutCustomerWhatsAppContact;

/// <summary>Stop documents to a number on every customer it is saved on.</summary>
public sealed record OptOutCustomerWhatsAppContactCommand(int ContactId) : IRequest<ErrorOr<List<CustomerWhatsAppContactModel>>>;
