// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.OptOutCustomerWhatsAppContact;

/// <summary>Stop documents to a number on every customer it is saved on.</summary>
public sealed class OptOutCustomerWhatsAppContactHandler(
    ICustomerDocumentService service,
    ILogger<OptOutCustomerWhatsAppContactHandler> logger
) : IRequestHandler<OptOutCustomerWhatsAppContactCommand, ErrorOr<List<CustomerWhatsAppContactModel>>>
{
    public Task<ErrorOr<List<CustomerWhatsAppContactModel>>> Handle(OptOutCustomerWhatsAppContactCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.OptOutContactAsync(request.ContactId, cancellationToken),
            "The number could not be opted out.",
            logger,
            "OptOutCustomerWhatsAppContact");
}
