// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.CheckWhatsAppNumber;

/// <summary>Whether a typed number is one, whether its owner opted out, and whether it is already saved.</summary>
public sealed record CheckWhatsAppNumberQuery(string Phone, string? CardCode, int? RouteCustomerId) : IRequest<ErrorOr<WhatsAppNumberCheckResultModel>>;
