// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.CheckWhatsAppNumber;

/// <summary>Whether a typed number is one, whether its owner opted out, and whether it is already saved.</summary>
public sealed class CheckWhatsAppNumberHandler(
    ICustomerDocumentService service,
    ILogger<CheckWhatsAppNumberHandler> logger
) : IRequestHandler<CheckWhatsAppNumberQuery, ErrorOr<WhatsAppNumberCheckResultModel>>
{
    public Task<ErrorOr<WhatsAppNumberCheckResultModel>> Handle(CheckWhatsAppNumberQuery request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.CheckPhoneAsync(request.Phone, request.CardCode, request.RouteCustomerId, cancellationToken),
            "The number could not be checked.",
            logger,
            "CheckWhatsAppNumber");
}
