"""Builds wwwroot/css/van-sales-documents.css from customer-app-access.css.

The Van Sales -> Invoices and Credit Notes pages share Customer App Access's Nocturne list: its token
aliases, dark-theme behaviour, buttons, fields, panels, grid-to-card layout and badges. Rather than a
hand-made copy that drifts, this renames the `caa` prefix to `vsd`, re-points the three card-layout cell
roles at generic names, drops the header comment and the onboarding form, and appends what a document
list needs that a sign-in list does not.

Run from the repository root:

    python scripts/make-van-sales-documents-css.py            # write the sheet
    python scripts/make-van-sales-documents-css.py --check    # fail if the checked-in sheet is stale
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "ShopInventory.Web/wwwroot/css/customer-app-access.css"
TARGET = ROOT / "ShopInventory.Web/wwwroot/css/van-sales-documents.css"

HEADER = """/* ==========================================================================
   Van Sales documents — Nocturne

   GENERATED by scripts/make-van-sales-documents-css.py from
   customer-app-access.css. Edit that script, not this file, and re-run it.

   Carries the two Van Sales document lists — /van-sales/invoices and
   /van-sales/credit-notes — under the `vsd` prefix. Everything above the
   "Documents" section is Customer App Access's sheet with its prefix renamed:
   the token aliases onto nocturne-tokens.css (so light and `.dark-theme` both
   follow the system), the two-class-deep control selectors that beat app.css's
   global dark-theme field rules, and the grid that re-lays as a card per row
   below 1040px. What follows it is only what a document list adds.
   ========================================================================== */

"""

EXTRA = """
/* ── Documents ─────────────────────────────────────────────────────────── */

/* Date and reference, customer, rep, amount, SAP number, receipt, state. */
.vsd .vsd-grid-invoices {
    --vsd-cols: minmax(0, 1.25fr) minmax(0, 1.4fr) minmax(0, 1fr) 118px 96px 128px 150px;
}

/* Date and number, customer, the van invoice it reverses, amount, receipt, state. */
.vsd .vsd-grid-credits {
    --vsd-cols: minmax(0, 1.1fr) minmax(0, 1.3fr) minmax(0, 1.4fr) 118px 128px 150px;
}

.vsd .vsd-row-button {
    width: 100%;
    border: 0;
    border-bottom: 1px solid var(--vsd-rule);
    background: transparent;
    color: inherit;
    font: inherit;
    text-align: left;
    cursor: pointer;
}

.vsd-num {
    font-size: 13.5px;
    color: var(--vsd-ink);
    font-variant-numeric: tabular-nums;
    white-space: nowrap;
}

.vsd-cell-amount {
    align-items: flex-end;
    text-align: right;
}

.vsd-net {
    font-size: 10.5px;
    letter-spacing: .06em;
    text-transform: uppercase;
    color: var(--vsd-faint);
}

.vsd-problem {
    font-size: 11.5px;
    color: var(--vsd-fam-bad);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.vsd-fam-good {
    color: var(--vsd-fam-good);
    background: rgba(var(--vsd-fam-good-rgb), .12);
    box-shadow: inset 0 0 0 1px rgba(var(--vsd-fam-good-rgb), .3);
}

.vsd-fam-warn {
    color: var(--vsd-fam-warn);
    background: rgba(var(--vsd-fam-warn-rgb), .12);
    box-shadow: inset 0 0 0 1px rgba(var(--vsd-fam-warn-rgb), .3);
}

/* The state filter doubles as the counts: each option says how many it would show.
   A row, not the inherited grid, which would stack the count under its label. */
.vsd .vsd-seg-opt {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
}

.vsd .vsd-seg-opt .vsd-seg-count {
    font-variant-numeric: tabular-nums;
    color: var(--vsd-mute-3);
}

.vsd .vsd-seg-opt.is-on .vsd-seg-count {
    color: inherit;
}

/* Six states and their counts do not fit a phone's width on one line, and a
   clipped filter hides the states most likely to need someone. They wrap. */
@media (max-width: 860px) {
    .vsd-seg {
        flex: 1 1 100%;
        flex-wrap: wrap;
    }

    .vsd .vsd-seg-opt {
        flex: 1 1 auto;
    }
}

.vsd .vsd-input-date {
    width: 150px;
}

.vsd-note {
    display: flex;
    gap: var(--vsd-s3);
    align-items: flex-start;
    margin: 0 var(--vsd-s6) var(--vsd-s4);
    padding: var(--vsd-s3) var(--vsd-s4);
    border-radius: var(--vsd-r-md);
    font-size: 12.5px;
    color: var(--vsd-fam-warn);
    background: rgba(var(--vsd-fam-warn-rgb), .1);
}

.vsd-pager {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--vsd-s4);
    padding: var(--vsd-s3) var(--vsd-s6);
    border-top: 1px solid var(--vsd-rule);
    font-size: 12.5px;
    color: var(--vsd-mute-3);
}

.vsd-pager-buttons {
    display: flex;
    gap: var(--vsd-s2);
}

/* ── The detail panel ──────────────────────────────────────────────────── */
/* Opens from the right over the list rather than replacing it, so the operator
   keeps their place in a long day. Outside `.vsd` for the reason the dialog is. */

.vsd-overlay.vsd-overlay-side {
    place-items: stretch end;
    padding: 0;
}

.vsd-drawer {
    width: min(560px, 100%);
    height: 100%;
    display: flex;
    flex-direction: column;
    background: var(--vsd-surface);
    box-shadow: var(--vsd-shadow-pop);
    overflow: hidden;
}

.vsd-drawer .vsd-dialog-body {
    flex: 1;
    gap: var(--vsd-s4);
}

.vsd-kv {
    display: grid;
    grid-template-columns: 140px minmax(0, 1fr);
    gap: 6px var(--vsd-s4);
    margin: 0;
    font-size: 13px;
}

.vsd-kv dt {
    color: var(--vsd-mute-3);
    font-weight: 400;
}

.vsd-kv dd {
    margin: 0;
    color: var(--vsd-ink);
    overflow-wrap: anywhere;
}

.vsd-section-title {
    margin: var(--vsd-s2) 0 0;
    font-size: 10.5px;
    letter-spacing: .1em;
    text-transform: uppercase;
    color: var(--vsd-mute-3);
}

.vsd-lines {
    width: 100%;
    border-collapse: collapse;
    font-size: 12.5px;
    color: var(--vsd-ink);
}

.vsd-lines th {
    padding: 6px 8px;
    border-bottom: 1px solid var(--vsd-rule);
    font-size: 10.5px;
    font-weight: 400;
    letter-spacing: .08em;
    text-transform: uppercase;
    text-align: left;
    color: var(--vsd-mute-3);
}

.vsd-lines td {
    padding: 6px 8px;
    border-bottom: 1px solid var(--vsd-rule);
    vertical-align: top;
}

.vsd-lines .vsd-r {
    text-align: right;
    font-variant-numeric: tabular-nums;
    white-space: nowrap;
}

.vsd-qr {
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 11.5px;
    color: var(--vsd-mute-2);
    overflow-wrap: anywhere;
}
"""


def build() -> str:
    text = SOURCE.read_text(encoding="utf-8").replace("\r\n", "\n")

    # The source's own header describes the sign-in page; this sheet carries its own.
    body = text[text.index(".caa,\n.caa-overlay {"):]

    # The onboarding form's section is kept whole: it also carries the message box both pages use for a
    # failed load, and a stripped copy lost it once already.
    body = body.replace("caa", "vsd")

    # The card layout's cell roles, named for what they hold on any list rather than on a sign-in.
    body = body.replace(".vsd-cell-shop {", ".vsd-cell-main {")
    body = body.replace(".vsd-cell-status {", ".vsd-cell-state {")
    body = body.replace(
        ".vsd-cell-phone,\n    .vsd-cell-holder,\n    .vsd-cell-seen {",
        ".vsd-cell-sub {")

    for required in (".vsd-msg {", ".vsd-seg {", ".vsd-badge {", ".vsd-overlay {"):
        if required not in body:
            raise SystemExit(f"{required} is missing from the generated sheet; the pages use it.")

    for leftover in ("vsd-cell-shop", "vsd-cell-status", "vsd-cell-phone", "vsd-cell-holder", "vsd-cell-seen"):
        if leftover in body:
            raise SystemExit(f"{leftover} survived the rename; the source sheet has changed shape.")

    return (HEADER + body.rstrip() + "\n" + EXTRA).replace("\n", "\r\n")


def main() -> None:
    sheet = build()

    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current.replace("\r\n", "\n") != sheet.replace("\r\n", "\n"):
            raise SystemExit(f"{TARGET.name} is stale: re-run scripts/make-van-sales-documents-css.py.")
        print(f"{TARGET.name} is current.")
        return

    TARGET.write_bytes(sheet.encode("utf-8"))
    print(f"Wrote {TARGET.relative_to(ROOT)} ({sheet.count(chr(10))} lines).")


if __name__ == "__main__":
    main()
