"""Writes find-stale-reposted-links.sql: which local rows still name an invoice's pre-rollback numbers.

After the September 2026 SAP rollback, ~1,560 invoices were reposted by the separate "Invoice back
posting" tool. Each repost's Comments start "Invoice posted from SAP update. Old invoice <n>." and most
carry the sale's "Ref <reference>". ShopInventory was never told the new numbers, and SAP has since
reissued the old DocEntries and DocNums to other documents — so a local row holding an old number now
names someone else's invoice. Memo 59606 (Cheese Galore) showed against a $50 van sale that way.

The SQL is generated, not hand-written: the reposts are read from SAP and inlined as a VALUES list, and
the script itself only reads (BEGIN READ ONLY ... ROLLBACK). Run it on the API box with
Find-StaleRepostedLinks.ps1.

    # read-only GETs against production; the session id is a pasted POST /Login reply
    SAP_B1SESSION=<SessionId> python scripts/stale_reposted_links.py
    python scripts/stale_reposted_links.py --from-json reposted.json   # offline, from a saved pull
"""
import argparse
import json
import os
import re
import sys

MARKER = "Invoice posted from SAP update"
OLD = re.compile(r"Old invoice (\d+)")
REF = re.compile(r"\bRef ([A-Za-z0-9][A-Za-z0-9-]*)")


def pull_from_sap(base_url, session):
    import requests
    import urllib3

    urllib3.disable_warnings()
    s = requests.Session()
    s.verify = False  # self-signed CN=kfldb; this only reads
    s.cookies.set("B1SESSION", session)
    url = (base_url + "Invoices?$filter=startswith(Comments,'" + MARKER + "')"
           "&$select=DocEntry,DocNum,DocDate,CardCode,Comments,DocTotal&$orderby=DocEntry")
    rows = []
    while url:
        r = s.get(url, headers={"Prefer": "odata.maxpagesize=500"}, timeout=300)
        r.raise_for_status()
        body = r.json()
        rows += body["value"]
        nxt = body.get("odata.nextLink")
        url = base_url + nxt if nxt else None
    return rows


def sql_text(value):
    return "NULL" if value is None else "'" + str(value).replace("'", "''") + "'"


def values_block(reposts):
    lines = []
    for r in reposts:
        old = OLD.search(r["Comments"] or "")
        ref = REF.search(r["Comments"] or "")
        if not old:
            raise SystemExit(f"repost DocEntry {r['DocEntry']} has no 'Old invoice <n>' in its Comments")
        lines.append(
            f"({r['DocEntry']},{r['DocNum']},{old.group(1)},{sql_text((r['CardCode'] or '').strip())},"
            f"{sql_text(ref.group(1) if ref else None)},{r['DocTotal']},DATE {sql_text(r['DocDate'][:10])})")
    return ",\n".join(lines)


def render(reposts):
    repost_cte = (
        "repost(new_entry, new_num, old_num, card, ref, total, doc_date) AS (VALUES\n"
        + values_block(reposts) + ")")

    # Every local row that names a reposted sale, with what it holds against what SAP now says.
    stale_cte = """
sale_rows AS (
    SELECT 'DesktopSales' AS tbl, s."Id"::text AS row_id, s."SourceSystem" AS source, s."ExternalReferenceId" AS ref,
           s."SapDocEntry" AS stored_entry, s."SapDocNum" AS stored_num
      FROM "DesktopSales" s
    UNION ALL
    SELECT 'StockReservations', r."Id"::text, r."SourceSystem", r."ExternalReferenceId", r."SAPDocEntry", r."SAPDocNum"
      FROM "StockReservations" r
    UNION ALL
    SELECT 'InvoiceQueue', q."Id"::text, q."SourceSystem", q."ExternalReference",
           CASE WHEN q."SapDocEntry" ~ '^[0-9]+$' THEN q."SapDocEntry"::int END, q."SapDocNum"
      FROM "InvoiceQueue" q
),
stale AS (
    SELECT x.tbl, x.row_id, x.source, p.ref, p.card, x.stored_entry, x.stored_num,
           p.new_entry, p.new_num, p.old_num, p.total, p.doc_date,
           CASE WHEN x.stored_num IS NULL AND x.stored_entry IS NULL THEN 'no number recorded'
                WHEN x.stored_num = p.old_num THEN 'holds the OLD invoice'
                ELSE 'holds some other number' END AS verdict
      FROM sale_rows x
      JOIN repost p ON p.ref = x.ref
     WHERE x.stored_entry IS DISTINCT FROM p.new_entry OR x.stored_num IS DISTINCT FROM p.new_num
)"""

    head = "WITH " + repost_cte + "," + stale_cte

    return f"""-- Generated by scripts/stale_reposted_links.py from {len(reposts)} reposted invoices. Do not edit by hand.
-- Read-only: nothing here writes, and the transaction is rolled back.
\\pset footer on
BEGIN TRANSACTION READ ONLY;

\\echo
\\echo '== 1. Local rows of reposted sales that do not hold the repost''s numbers (per table and verdict)'
{head}
SELECT tbl, source, verdict, count(*) AS rows, count(DISTINCT ref) AS sales
  FROM stale GROUP BY 1, 2, 3 ORDER BY 1, 2, 3;

\\echo
\\echo '== 2. Credit memos the projection ties to a stale DocEntry (these show against the wrong sale)'
{head}
SELECT DISTINCT c."SapDocNum" AS memo, c."CardCode" AS memo_card, c."DocTotal" AS memo_total, c."IsCancelled",
       c."DocDate"::date AS memo_date, l."BaseEntry" AS based_on_entry,
       st.ref AS shown_against_sale, st.card AS sale_card, st.total AS sale_total, st.new_num AS sale_real_invoice
  FROM "SapCreditNoteSnapshots" c
  JOIN "SapCreditNoteLineSnapshots" l ON l."CreditNoteDocEntry" = c."SapDocEntry" AND l."BaseType" = 13
  JOIN stale st ON st.stored_entry = l."BaseEntry"
 ORDER BY memo;

\\echo
\\echo '== 3. Till credits raised against reposted sales whose row holds a stale DocEntry (the poster reads that invoice)'
{head}
SELECT d."Number", d."Status", d."SapStatus", d."SapDocNum" AS memo, d."Amount", d."CreatedAtUtc",
       st.ref, st.stored_entry, st.new_entry, st.verdict
  FROM "DesktopCreditNotes" d
  JOIN stale st ON st.tbl = 'DesktopSales' AND st.row_id = d."SaleId"::text
 ORDER BY d."CreatedAtUtc";

\\echo
\\echo '== 4. App credit notes whose original invoice is a stale DocEntry'
{head}
SELECT DISTINCT n."CreditNoteNumber", n."SAPDocNum", n."CardCode", n."DocTotal", n."OriginalInvoiceDocEntry",
       st.ref, st.new_entry
  FROM "CreditNotes" n
  JOIN stale st ON st.stored_entry = n."OriginalInvoiceDocEntry"
 ORDER BY 1;

\\echo
\\echo '== 5. Rows keyed only by invoice number that still hold an old DocNum (matched on customer where the table has one)'
WITH {repost_cte}
SELECT 'Invoices' AS tbl, i."Id"::text AS row_id, i."CardCode" AS card, i."SAPDocNum" AS stored_num,
       p.old_num, p.new_num, p.new_entry
  FROM "Invoices" i JOIN repost p ON p.old_num = i."SAPDocNum" AND p.card = i."CardCode"
UNION ALL
SELECT 'DailyIncomingPaymentLines', l."Id"::text, NULL, l."InvoiceDocNum", p.old_num, p.new_num, p.new_entry
  FROM "DailyIncomingPaymentLines" l JOIN repost p ON p.old_num = l."InvoiceDocNum"
UNION ALL
SELECT 'CrateTransactions', t."Id"::text, t."ShopCardCode", t."InvoiceDocNum", p.old_num, p.new_num, p.new_entry
  FROM "CrateTransactions" t JOIN repost p ON p.old_num = t."InvoiceDocNum"
 ORDER BY 1, 4;

\\echo
\\echo '== 6. Every stale sale row, for the repair'
{head}
SELECT tbl, row_id, source, ref, card, stored_entry, stored_num, new_entry, new_num, old_num, verdict
  FROM stale ORDER BY ref, tbl;

ROLLBACK;
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--from-json", help="a saved pull: a JSON list of the reposted invoices")
    ap.add_argument("--save-json", help="also save the SAP pull here")
    ap.add_argument("--base-url", default="https://10.10.10.6:50000/b1s/v1/")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                  "find-stale-reposted-links.sql"))
    args = ap.parse_args()

    if args.from_json:
        with open(args.from_json, encoding="utf-8") as f:
            reposts = json.load(f)
    else:
        session = os.environ.get("SAP_B1SESSION")
        if not session:
            sys.exit("Set SAP_B1SESSION to a production session id, or pass --from-json.")
        reposts = pull_from_sap(args.base_url, session)
        if args.save_json:
            with open(args.save_json, "w", encoding="utf-8") as f:
                json.dump(reposts, f)

    reposts = [r for r in reposts if (r.get("Comments") or "").startswith(MARKER)]
    with open(args.out, "w", encoding="ascii", errors="strict", newline="\n") as f:
        f.write(render(reposts))

    with_ref = sum(1 for r in reposts if REF.search(r["Comments"] or ""))
    print(f"{len(reposts)} reposts ({with_ref} with a sale reference) -> {args.out}")


if __name__ == "__main__":
    main()
