-- Proves the BackfillShopsFromTillAccounts migration SQL against a real PostgreSQL.
-- Runs in a throwaway database; touches nothing of the developer's own.

CREATE TABLE "Shops" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(30) NOT NULL,
    "Name" varchar(100) NOT NULL,
    "BusinessPartnerCode" varchar(100) NOT NULL,
    "WarehouseCode" varchar(50) NOT NULL,
    "CostCentreCode" varchar(50) NULL,
    "IsActive" boolean NOT NULL,
    "CreatedByUserId" uuid NULL,
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedByUserId" uuid NULL,
    "UpdatedAt" timestamptz NULL
);

CREATE TABLE "Users" (
    "Id" uuid PRIMARY KEY,
    "Username" varchar(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "Role" varchar(50) NOT NULL,
    "AssignedWarehouseCodes" varchar(500) NULL,
    "AssignedBusinessPartnerCode" varchar(100) NULL,
    "AssignedCostCentreCode" varchar(50) NULL,
    "ShopId" integer NULL REFERENCES "Shops"("Id")
);

-- Farm: two accounts that agree. Expect a shop, and both assigned.
INSERT INTO "Users" VALUES
  (gen_random_uuid(), 'farm1', TRUE, 'Cashier', '["KEFSHOP"]', 'FARM-BP', 'CC-FARM', NULL),
  (gen_random_uuid(), 'farm2', TRUE, 'Cashier', '["KEFSHOP"]', 'FARM-BP', 'CC-FARM', NULL);

-- An inactive account at Farm on a different partner. Must not spoil the agreement.
INSERT INTO "Users" VALUES
  (gen_random_uuid(), 'farm-old', FALSE, 'Cashier', '["KEFSHOP"]', 'WRONG-BP', 'CC-X', NULL);

-- A multi-warehouse account. Not a till; must be ignored entirely.
INSERT INTO "Users" VALUES
  (gen_random_uuid(), 'stock1', TRUE, 'StockController', '["KEFSHOP","KEFGRS"]', 'OTHER-BP', 'CC-Y', NULL);

-- Graniteside: two accounts that disagree on the business partner. Expect NO shop.
INSERT INTO "Users" VALUES
  (gen_random_uuid(), 'gran1', TRUE, 'Cashier', '["KEFGRS"]', 'GRAN-BP-A', 'CC-G', NULL),
  (gen_random_uuid(), 'gran2', TRUE, 'Cashier', '["KEFGRS"]', 'GRAN-BP-B', 'CC-G', NULL);

-- Machipisa: one account, no cost centre. Expect a shop with a null cost centre, and it assigned.
INSERT INTO "Users" VALUES
  (gen_random_uuid(), 'mach1', TRUE, 'Cashier', '["CORMACH2"]', 'MACH-BP', NULL, NULL);

-- ===== The migration's Up(), verbatim =====

WITH known_shops(code, name, warehouse) AS (
    VALUES ('FARM', 'Farm', 'KEFSHOP'),
           ('GRANITESIDE', 'Graniteside', 'KEFGRS'),
           ('MACHIPISA', 'Machipisa', 'CORMACH2')
),
till_accounts AS (
    SELECT
        upper(u."AssignedWarehouseCodes") AS warehouse_json,
        btrim(u."AssignedBusinessPartnerCode") AS business_partner,
        NULLIF(btrim(COALESCE(u."AssignedCostCentreCode", '')), '') AS cost_centre
    FROM "Users" u
    WHERE u."IsActive"
      AND u."ShopId" IS NULL
      AND u."AssignedBusinessPartnerCode" IS NOT NULL
      AND btrim(u."AssignedBusinessPartnerCode") <> ''
),
derived AS (
    SELECT
        ks.code,
        ks.name,
        ks.warehouse,
        min(ta.business_partner) AS business_partner,
        min(ta.cost_centre) AS cost_centre,
        count(DISTINCT ta.business_partner) AS business_partner_variants,
        count(DISTINCT COALESCE(ta.cost_centre, '')) AS cost_centre_variants
    FROM known_shops ks
    JOIN till_accounts ta
      ON ta.warehouse_json = '["' || upper(ks.warehouse) || '"]'
    GROUP BY ks.code, ks.name, ks.warehouse
)
INSERT INTO "Shops"
    ("Code", "Name", "BusinessPartnerCode", "WarehouseCode", "CostCentreCode", "IsActive", "CreatedAt")
SELECT d.code, d.name, d.business_partner, d.warehouse, d.cost_centre, TRUE, now()
FROM derived d
WHERE d.business_partner_variants = 1
  AND d.cost_centre_variants = 1
  AND NOT EXISTS (
      SELECT 1 FROM "Shops" s
      WHERE upper(s."Code") = upper(d.code)
         OR upper(s."WarehouseCode") = upper(d.warehouse));

UPDATE "Users" u
SET "ShopId" = s."Id"
FROM "Shops" s
WHERE u."ShopId" IS NULL
  AND u."IsActive"
  AND upper(u."AssignedWarehouseCodes") = '["' || upper(s."WarehouseCode") || '"]'
  AND upper(btrim(u."AssignedBusinessPartnerCode")) = upper(btrim(s."BusinessPartnerCode"))
  AND COALESCE(NULLIF(btrim(u."AssignedCostCentreCode"), ''), '')
      = COALESCE(NULLIF(btrim(COALESCE(s."CostCentreCode", '')), ''), '');

-- ===== What it did =====

\echo '--- Shops created ---'
SELECT "Code", "Name", "BusinessPartnerCode", "WarehouseCode", COALESCE("CostCentreCode", '(null)') AS cc
FROM "Shops" ORDER BY "Code";

\echo '--- User assignments ---'
SELECT u."Username", COALESCE(s."Code", '(unassigned)') AS shop
FROM "Users" u LEFT JOIN "Shops" s ON s."Id" = u."ShopId"
ORDER BY u."Username";

\echo '--- Expectations ---'
SELECT
  (SELECT count(*) FROM "Shops") = 2                                              AS two_shops_created,
  (SELECT count(*) FROM "Shops" WHERE "Code" = 'GRANITESIDE') = 0                 AS disagreeing_warehouse_skipped,
  (SELECT "CostCentreCode" IS NULL FROM "Shops" WHERE "Code" = 'MACHIPISA')       AS null_cost_centre_preserved,
  (SELECT count(*) FROM "Users" WHERE "ShopId" IS NOT NULL) = 3                   AS three_users_assigned,
  (SELECT "ShopId" IS NULL FROM "Users" WHERE "Username" = 'farm-old')            AS inactive_left_alone,
  (SELECT "ShopId" IS NULL FROM "Users" WHERE "Username" = 'stock1')              AS multi_warehouse_left_alone,
  (SELECT "ShopId" IS NULL FROM "Users" WHERE "Username" = 'gran1')               AS disagreeing_users_left_alone;

-- ===== The migration's Down(), verbatim =====

UPDATE "Users" u
SET "ShopId" = NULL
FROM "Shops" s
WHERE u."ShopId" = s."Id"
  AND upper(s."Code") IN ('FARM', 'GRANITESIDE', 'MACHIPISA');

DELETE FROM "Shops" s
WHERE upper(s."Code") IN ('FARM', 'GRANITESIDE', 'MACHIPISA')
  AND NOT EXISTS (SELECT 1 FROM "Users" u WHERE u."ShopId" = s."Id");

\echo '--- After Down ---'
SELECT
  (SELECT count(*) FROM "Shops") = 0                            AS shops_removed,
  (SELECT count(*) FROM "Users" WHERE "ShopId" IS NOT NULL) = 0 AS users_released;
