// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.RecheckCustomerWhatsAppContact;

/// <summary>Ask WhatsApp now whether a saved number has an account.</summary>
public sealed record RecheckCustomerWhatsAppContactCommand(int ContactId) : IRequest<ErrorOr<CustomerWhatsAppContactModel>>;
