// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.RecheckCustomerWhatsAppContact;

/// <summary>Ask WhatsApp now whether a saved number has an account.</summary>
public sealed class RecheckCustomerWhatsAppContactHandler(
    ICustomerDocumentService service,
    ILogger<RecheckCustomerWhatsAppContactHandler> logger
) : IRequestHandler<RecheckCustomerWhatsAppContactCommand, ErrorOr<CustomerWhatsAppContactModel>>
{
    public Task<ErrorOr<CustomerWhatsAppContactModel>> Handle(RecheckCustomerWhatsAppContactCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.RecheckContactAsync(request.ContactId, cancellationToken),
            "WhatsApp could not be asked about the number.",
            logger,
            "RecheckCustomerWhatsAppContact");
}
