// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.RemoveCustomerWhatsAppContact;

/// <summary>Take a number off one customer. The record stays for what was sent to it.</summary>
public sealed record RemoveCustomerWhatsAppContactCommand(int ContactId) : IRequest<ErrorOr<Success>>;
