// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.RemoveCustomerWhatsAppContact;

/// <summary>Take a number off one customer. The record stays for what was sent to it.</summary>
public sealed class RemoveCustomerWhatsAppContactHandler(
    ICustomerDocumentService service,
    ILogger<RemoveCustomerWhatsAppContactHandler> logger
) : IRequestHandler<RemoveCustomerWhatsAppContactCommand, ErrorOr<Success>>
{
    public Task<ErrorOr<Success>> Handle(RemoveCustomerWhatsAppContactCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync<Success>(
            async () =>
            {
                await service.RemoveContactAsync(request.ContactId, cancellationToken);
                return Result.Success;
            },
            "The number could not be removed.",
            logger,
            "RemoveCustomerWhatsAppContact");
}
