// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.GetCustomerDocumentDeliveryLog;

/// <summary>A page of the whole delivery log, for administrators.</summary>
public sealed record GetCustomerDocumentDeliveryLogQuery(string? Status, string? Trigger, string? Search, DateTime? FromDate, DateTime? ToDate, int Page, int PageSize) : IRequest<ErrorOr<CustomerDocumentDeliveryPageModel>>;
