// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.GetCustomerDocumentDeliveryLog;

/// <summary>A page of the whole delivery log, for administrators.</summary>
public sealed class GetCustomerDocumentDeliveryLogHandler(
    ICustomerDocumentService service,
    ILogger<GetCustomerDocumentDeliveryLogHandler> logger
) : IRequestHandler<GetCustomerDocumentDeliveryLogQuery, ErrorOr<CustomerDocumentDeliveryPageModel>>
{
    public Task<ErrorOr<CustomerDocumentDeliveryPageModel>> Handle(GetCustomerDocumentDeliveryLogQuery request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.GetLogAsync(request.Status, request.Trigger, request.Search, request.FromDate, request.ToDate, request.Page, request.PageSize, cancellationToken),
            "The delivery log could not be loaded.",
            logger,
            "GetCustomerDocumentDeliveryLog");
}
