// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.GetInvoiceWhatsAppDeliveries;

/// <summary>Every WhatsApp send of one invoice, newest first.</summary>
public sealed class GetInvoiceWhatsAppDeliveriesHandler(
    ICustomerDocumentService service,
    ILogger<GetInvoiceWhatsAppDeliveriesHandler> logger
) : IRequestHandler<GetInvoiceWhatsAppDeliveriesQuery, ErrorOr<List<CustomerDocumentDeliveryModel>>>
{
    public Task<ErrorOr<List<CustomerDocumentDeliveryModel>>> Handle(GetInvoiceWhatsAppDeliveriesQuery request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.GetInvoiceDeliveriesAsync(request.DocEntry, cancellationToken),
            "The invoice's WhatsApp history could not be loaded.",
            logger,
            "GetInvoiceWhatsAppDeliveries");
}
