// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Queries.GetInvoiceWhatsAppDeliveries;

/// <summary>Every WhatsApp send of one invoice, newest first.</summary>
public sealed record GetInvoiceWhatsAppDeliveriesQuery(int DocEntry) : IRequest<ErrorOr<List<CustomerDocumentDeliveryModel>>>;
