// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.SaveCustomerWhatsAppContact;

/// <summary>Save a number a customer gave for their documents, with their consent.</summary>
public sealed record SaveCustomerWhatsAppContactCommand(SaveCustomerWhatsAppContactModel Contact) : IRequest<ErrorOr<List<CustomerWhatsAppContactModel>>>;
