// Generated by scripts/gen_web_customer_document_handlers.py; edit the generator, not this file.
using ErrorOr;
using MediatR;
using ShopInventory.Web.Models;
using ShopInventory.Web.Services;

namespace ShopInventory.Web.Features.CustomerDocuments.Commands.SaveCustomerWhatsAppContact;

/// <summary>Save a number a customer gave for their documents, with their consent.</summary>
public sealed class SaveCustomerWhatsAppContactHandler(
    ICustomerDocumentService service,
    ILogger<SaveCustomerWhatsAppContactHandler> logger
) : IRequestHandler<SaveCustomerWhatsAppContactCommand, ErrorOr<List<CustomerWhatsAppContactModel>>>
{
    public Task<ErrorOr<List<CustomerWhatsAppContactModel>>> Handle(SaveCustomerWhatsAppContactCommand request, CancellationToken cancellationToken) =>
        CustomerDocumentCall.RunAsync(
            () => service.SaveContactAsync(request.Contact, cancellationToken),
            "The WhatsApp number could not be saved.",
            logger,
            "SaveCustomerWhatsAppContact");
}
