CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260104055937_InitialCreate') THEN
    CREATE TABLE "CachedProducts" (
        "ItemCode" character varying(50) NOT NULL,
        "ItemName" character varying(200),
        "BarCode" character varying(50),
        "ItemType" character varying(20),
        "ManagesBatches" boolean NOT NULL,
        "Price" numeric(18,6) NOT NULL,
        "DefaultWarehouse" character varying(20),
        "UoM" character varying(20),
        "LastSyncedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_CachedProducts" PRIMARY KEY ("ItemCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260104055937_InitialCreate') THEN
    CREATE TABLE "CacheSyncInfo" (
        "CacheKey" character varying(50) NOT NULL,
        "LastSyncedAt" timestamp with time zone NOT NULL,
        "ItemCount" integer NOT NULL,
        "SyncSuccessful" boolean NOT NULL,
        "LastError" character varying(500),
        CONSTRAINT "PK_CacheSyncInfo" PRIMARY KEY ("CacheKey")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260104055937_InitialCreate') THEN
    CREATE INDEX "IX_CachedProducts_BarCode" ON "CachedProducts" ("BarCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260104055937_InitialCreate') THEN
    CREATE INDEX "IX_CachedProducts_IsActive" ON "CachedProducts" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260104055937_InitialCreate') THEN
    CREATE INDEX "IX_CachedProducts_ItemName" ON "CachedProducts" ("ItemName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260104055937_InitialCreate') THEN
    CREATE INDEX "IX_CachedProducts_LastSyncedAt" ON "CachedProducts" ("LastSyncedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260104055937_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260104055937_InitialCreate', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE TABLE "AppSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Category" character varying(50) NOT NULL,
        "Key" character varying(100) NOT NULL,
        "Value" character varying(500) NOT NULL,
        "DataType" character varying(20) NOT NULL,
        "Description" character varying(500),
        "IsVisible" boolean NOT NULL,
        "IsEditable" boolean NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "LastModifiedAt" timestamp with time zone NOT NULL,
        "LastModifiedBy" character varying(100),
        CONSTRAINT "PK_AppSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(100) NOT NULL,
        "UserRole" character varying(50) NOT NULL,
        "Action" character varying(100) NOT NULL,
        "EntityType" character varying(100),
        "EntityId" character varying(100),
        "Details" character varying(1000),
        "IpAddress" character varying(50),
        "UserAgent" character varying(500),
        "PageUrl" character varying(500),
        "IsSuccess" boolean NOT NULL,
        "ErrorMessage" character varying(1000),
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE TABLE "CachedBusinessPartners" (
        "CardCode" character varying(50) NOT NULL,
        "CardName" character varying(200),
        "CardType" character varying(10),
        "GroupCode" character varying(20),
        "Phone1" character varying(50),
        "Phone2" character varying(50),
        "Email" character varying(100),
        "Address" character varying(500),
        "City" character varying(100),
        "Country" character varying(50),
        "Currency" character varying(10),
        "Balance" numeric(18,6),
        "IsActive" boolean NOT NULL,
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CachedBusinessPartners" PRIMARY KEY ("CardCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE TABLE "CachedGLAccounts" (
        "Code" character varying(50) NOT NULL,
        "Name" character varying(200),
        "AccountType" character varying(50),
        "Currency" character varying(10),
        "Balance" numeric(18,6) NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CachedGLAccounts" PRIMARY KEY ("Code")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE TABLE "CachedPrices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ItemCode" character varying(50) NOT NULL,
        "ItemName" character varying(200),
        "Price" numeric(18,6) NOT NULL,
        "Currency" character varying(10),
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CachedPrices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE TABLE "CachedWarehouses" (
        "WarehouseCode" character varying(20) NOT NULL,
        "WarehouseName" character varying(100),
        "Location" character varying(200),
        "Street" character varying(200),
        "City" character varying(100),
        "Country" character varying(50),
        "IsActive" boolean NOT NULL,
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CachedWarehouses" PRIMARY KEY ("WarehouseCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    INSERT INTO "CachedWarehouses" ("WarehouseCode", "City", "Country", "IsActive", "LastSyncedAt", "Location", "Street", "WarehouseName")
    VALUES ('01', NULL, NULL, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Main', NULL, 'General Warehouse');
    INSERT INTO "CachedWarehouses" ("WarehouseCode", "City", "Country", "IsActive", "LastSyncedAt", "Location", "Street", "WarehouseName")
    VALUES ('02', NULL, NULL, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Secondary', NULL, 'Warehouse 02');
    INSERT INTO "CachedWarehouses" ("WarehouseCode", "City", "Country", "IsActive", "LastSyncedAt", "Location", "Street", "WarehouseName")
    VALUES ('03', NULL, NULL, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Tertiary', NULL, 'Warehouse 03');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_AppSettings_Category" ON "AppSettings" ("Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE UNIQUE INDEX "IX_AppSettings_Key" ON "AppSettings" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_AuditLogs_Action" ON "AuditLogs" ("Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp_Username" ON "AuditLogs" ("Timestamp", "Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_AuditLogs_Username" ON "AuditLogs" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedBusinessPartners_CardName" ON "CachedBusinessPartners" ("CardName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedBusinessPartners_CardType" ON "CachedBusinessPartners" ("CardType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedBusinessPartners_IsActive" ON "CachedBusinessPartners" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedGLAccounts_AccountType" ON "CachedGLAccounts" ("AccountType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedGLAccounts_IsActive" ON "CachedGLAccounts" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedGLAccounts_Name" ON "CachedGLAccounts" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedPrices_Currency" ON "CachedPrices" ("Currency");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedPrices_ItemCode" ON "CachedPrices" ("ItemCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE UNIQUE INDEX "IX_CachedPrices_ItemCode_Currency" ON "CachedPrices" ("ItemCode", "Currency");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedWarehouses_IsActive" ON "CachedWarehouses" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    CREATE INDEX "IX_CachedWarehouses_WarehouseName" ON "CachedWarehouses" ("WarehouseName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106102439_SeedDefaultWarehouses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260106102439_SeedDefaultWarehouses', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106110424_AddCachedWarehouseStock') THEN
    CREATE TABLE "CachedWarehouseStocks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ItemCode" character varying(50) NOT NULL,
        "ItemName" character varying(200),
        "BarCode" character varying(50),
        "WarehouseCode" character varying(20) NOT NULL,
        "InStock" numeric(18,6) NOT NULL,
        "Committed" numeric(18,6) NOT NULL,
        "Ordered" numeric(18,6) NOT NULL,
        "Available" numeric(18,6) NOT NULL,
        "UoM" character varying(20),
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CachedWarehouseStocks" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106110424_AddCachedWarehouseStock') THEN
    CREATE INDEX "IX_CachedWarehouseStocks_BarCode" ON "CachedWarehouseStocks" ("BarCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106110424_AddCachedWarehouseStock') THEN
    CREATE INDEX "IX_CachedWarehouseStocks_ItemCode" ON "CachedWarehouseStocks" ("ItemCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106110424_AddCachedWarehouseStock') THEN
    CREATE INDEX "IX_CachedWarehouseStocks_LastSyncedAt" ON "CachedWarehouseStocks" ("LastSyncedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106110424_AddCachedWarehouseStock') THEN
    CREATE INDEX "IX_CachedWarehouseStocks_WarehouseCode" ON "CachedWarehouseStocks" ("WarehouseCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106110424_AddCachedWarehouseStock') THEN
    CREATE UNIQUE INDEX "IX_CachedWarehouseStocks_WarehouseCode_ItemCode" ON "CachedWarehouseStocks" ("WarehouseCode", "ItemCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106110424_AddCachedWarehouseStock') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260106110424_AddCachedWarehouseStock', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE TABLE "CachedIncomingPayments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DocEntry" integer NOT NULL,
        "DocNum" integer NOT NULL,
        "DocDate" timestamp with time zone,
        "DocDueDate" timestamp with time zone,
        "CardCode" character varying(50),
        "CardName" character varying(200),
        "DocCurrency" character varying(10),
        "CashSum" numeric(18,6) NOT NULL,
        "CheckSum" numeric(18,6) NOT NULL,
        "TransferSum" numeric(18,6) NOT NULL,
        "CreditSum" numeric(18,6) NOT NULL,
        "DocTotal" numeric(18,6) NOT NULL,
        "Remarks" character varying(500),
        "TransferReference" character varying(100),
        "TransferDate" timestamp with time zone,
        "TransferAccount" character varying(50),
        "PaymentInvoicesJson" text,
        "PaymentChecksJson" text,
        "PaymentCreditCardsJson" text,
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CachedIncomingPayments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE TABLE "CachedInventoryTransfers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DocEntry" integer NOT NULL,
        "DocNum" integer NOT NULL,
        "DocDate" timestamp with time zone,
        "DueDate" timestamp with time zone,
        "FromWarehouse" character varying(20),
        "ToWarehouse" character varying(20),
        "Comments" character varying(500),
        "LinesJson" text,
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CachedInventoryTransfers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedIncomingPayments_CardCode" ON "CachedIncomingPayments" ("CardCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedIncomingPayments_DocDate" ON "CachedIncomingPayments" ("DocDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE UNIQUE INDEX "IX_CachedIncomingPayments_DocEntry" ON "CachedIncomingPayments" ("DocEntry");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedIncomingPayments_DocNum" ON "CachedIncomingPayments" ("DocNum");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedIncomingPayments_LastSyncedAt" ON "CachedIncomingPayments" ("LastSyncedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedInventoryTransfers_DocDate" ON "CachedInventoryTransfers" ("DocDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE UNIQUE INDEX "IX_CachedInventoryTransfers_DocEntry" ON "CachedInventoryTransfers" ("DocEntry");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedInventoryTransfers_DocNum" ON "CachedInventoryTransfers" ("DocNum");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedInventoryTransfers_FromWarehouse" ON "CachedInventoryTransfers" ("FromWarehouse");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedInventoryTransfers_LastSyncedAt" ON "CachedInventoryTransfers" ("LastSyncedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    CREATE INDEX "IX_CachedInventoryTransfers_ToWarehouse" ON "CachedInventoryTransfers" ("ToWarehouse");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260106112608_AddPaymentAndTransferCache') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260106112608_AddPaymentAndTransferCache', '10.0.1');
    END IF;
END $EF$;
COMMIT;

